### ISSUE TITLE
Error when import xesmf

### ISSUE THREAD

**Issue by llccl** [FlexTRKR/PyFLEXTRKR#70]
Hi,
 After a successful install with current environment.yml (with conda v4.10 & mamba as recommended in userguid.md), an error occur when I try a testing python script:

```
(flexnew) llccll@llccll-desktop:/mnt/e/forubuntu/mountain_meiyu$ python run_mcs_tbpf_wrf.py config_wrf4km_mcs_tbpf_example.yml
Traceback (most recent call last):
  File "/mnt/e/forubuntu/mountain_meiyu/run_mcs_tbpf_wrf.py", line 7, in <module>
    from pyflextrkr.preprocess_wrf_tb_rainrate import preprocess_wrf_tb_rainrate
  File "/mnt/e/forubuntu/PyFLEXTRKR1/PyFLEXTRKR/pyflextrkr/preprocess_wrf_tb_rainrate.py", line 7, in <module>
    import xesmf as xe
  File "/home/llccll/anaconda3/envs/flexnew/lib/python3.10/site-packages/xesmf/__init__.py", line 4, in <module>
    from .frontend import Regridder, SpatialAverager
  File "/home/llccll/anaconda3/envs/flexnew/lib/python3.10/site-packages/xesmf/frontend.py", line 12, in <module>
    from .backend import Grid, LocStream, Mesh, add_corner, esmf_regrid_build, esmf_regrid_finalize
  File "/home/llccll/anaconda3/envs/flexnew/lib/python3.10/site-packages/xesmf/backend.py", line 21, in <module>
    import ESMF
ModuleNotFoundError: No module named 'ESMF'
```

I check the conda list/pip list, the xesmf version is 0.6.3 As recommened by an issue of xesmf (link:https://github.com/pangeo-data/xESMF/issues/218), I edit the envinroment.yml with '-xesmf=0.7.0' in the last line and re-install it, and this proble is perfectly solved.
I am not sure this problem occurs in other version of conda/mamba. Hopefully this can help.

Cheers!
Zhongxi

**Comment by feng045** [comment]
Thank you @llccl for raising this issue. Sorry about the late response. 
I just checked the environment.yml and I didn't specify a minimum version for xesmf. By default at install, conda/mamba should install the latest release version. In my own PyFLEXTRKR environment it is currently 0.7.1, so I never saw that error before. Hopefully this will not be an issue going forward as xesmf is currently on 0.8.2 in Conda.
I'm closing this issue for now.
