### ISSUE TITLE
when cauculate the movement of MCS the index 77773 is out of bounds for axis 0 with size 5109

### ISSUE THREAD

**Issue by feiduduyyc** [FlexTRKR/PyFLEXTRKR#95]
2024-05-07 15:36:55,053 - distributed.worker - WARNING - Compute Failed
Key:       movement_of_feature_fft-ff64e480-7cb3-4b1e-b6db-5e3a7c9c4862
Function:  execute_task
args:      ((<function movement_of_feature_fft at 0x153e524ff4c0>, (<class 'tuple'>, ['/data2/users/ycyang/MCS/2011//mcstracking/20110501.0000_20110930.2300/mcstrack_20110618_163000.nc', '/data2/users/ycyang/MCS/2011//mcstracking/20110501.0000_20110930.2300/mcstrack_20110618_173000.nc']), 5108, (<class 'dict'>, [['run_idfeature', True], ['run_tracksingle', True], ['run_gettracks', True], ['run_trackstats', True], ['run_identifymcs', True], ['run_matchpf', True], ['run_robustmcs', True], ['run_mapfeature', True], ['run_speed', True], ['run_parallel', 1], ['nprocesses', 8], ['dask_tmp_dir', '/tmp'], ['timeout', 360], ['startdate', '20110501.0000'], ['enddate', '20110930.2300'], ['time_format', 'yyyymoddhh'], ['databasename', 'merg_'], ['clouddata_path', '/data2/users/ycyang/IMERG_GPM/2011/'], ['root_path', '/data2/users/ycyang/MCS/2011/'], ['tracking_path_name', 'tracking'], ['stats_path_name', 'stats'], ['pixel_path_name', 'mcstracking'], ['landmask_filename', 'INPUT_DIR/IMERG_landmask_saag.nc'],
kwargs:    {}
Exception: "IndexError('index 77773 is out of bounds for axis 0 with size 5109')"

S1
S2
S3
S4
S5
S6
S7
S8
Traceback (most recent call last):
  File "/data2/users/ycyang/MCS/2011/run_mcs_tbpf.py", line 84, in <module>
    movement_speed(config)
  File "/data2/users/ycyang/PyFLEXTRKR/pyflextrkr/movement_speed.py", line 126, in movement_speed
    final_result = dask.compute(*results)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ycyang/anaconda3/flextrkr/lib/python3.11/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/users/ycyang/PyFLEXTRKR/pyflextrkr/movement_speed.py", line 231, in movement_of_feature_fft
    min_cloud_size = np.minimum(get_pixel_size_of_clouds(dset1, ntracks, tracknumber),
      ^^^^^^^^^^^^^^^^^
  File "/data2/users/ycyang/PyFLEXTRKR/pyflextrkr/movement_speed.py", line 316, in get_pixel_size_of_clouds
    storm_sizes[track] = counts
      ~~~~~~~~~^^^^^^^^

**Comment by feiduduyyc** [comment]
why do my tracknumber is so large

**Comment by feng045** [comment]
I'm not exactly sure why without looking at your data.  You should check your final MCS track stats file (in the /stats/mcs_tracks_final_yyyymodd.hhmm_yyyymodd.hhmm.nc) to see how many tracks you have. The header looks like this:

netcdf mcs_tracks_final_20060101.0000_20070101.0000 {
dimensions:
	**tracks = UNLIMITED ; // (34634 currently)**
	times = 400 ;
	mergers = 50 ;
	nmaxpf = 3 ;

Then in your pixel files, you should check those two files that crashed:
_mcstrack_20110618_163000.nc
mcstrack_20110618_173000.nc_

And see what the **cloudtracknumber** values are in those files.  They should not exceed the **tracks** dimension size of your stats file.
